#!/usr/bin/env python3
"""Generate the student deck (index.html) from the presenter deck (index.notes.html).

index.notes.html is the file you edit. It is gitignored and never published, so it
is the only place speaker notes live. This script strips every <aside class="notes">
block out of it and writes index.html, which is what GitHub Pages serves.

    python3 build.py            # build, print a summary
    python3 build.py --check    # exit 1 if index.html is stale, write nothing
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
SRC = ROOT / "index.notes.html"
OUT = ROOT / "index.html"

BANNER = (
    "<!-- GENERATED by build.py from index.notes.html — do not edit directly.\n"
    "     Speaker notes are stripped here; edit index.notes.html and re-run the build. -->\n"
)

ASIDE_OPEN = re.compile(r"<aside\b[^>]*>", re.I)
ASIDE_CLOSE = re.compile(r"</aside\s*>", re.I)
NOTES_OPEN = re.compile(r'<aside\b[^>]*\bclass\s*=\s*"[^"]*\bnotes\b[^"]*"[^>]*>', re.I)


def strip_notes(html):
    """Remove <aside class="notes">...</aside> blocks, honouring nested <aside> tags."""
    out, pos, removed = [], 0, 0
    while True:
        start = NOTES_OPEN.search(html, pos)
        if not start:
            out.append(html[pos:])
            return "".join(out), removed

        # Walk forward counting aside depth so a nested <aside> can't end the block early.
        depth, cursor = 1, start.end()
        while depth:
            nxt_open = ASIDE_OPEN.search(html, cursor)
            nxt_close = ASIDE_CLOSE.search(html, cursor)
            if not nxt_close:
                raise SystemExit(f"unclosed <aside class=\"notes\"> at offset {start.start()}")
            if nxt_open and nxt_open.start() < nxt_close.start():
                depth, cursor = depth + 1, nxt_open.end()
            else:
                depth, cursor = depth - 1, nxt_close.end()

        # Also swallow the leading indentation and the trailing newline of the block.
        line_start = html.rfind("\n", 0, start.start()) + 1
        keep_to = line_start if not html[line_start:start.start()].strip() else start.start()
        if html[cursor:cursor + 1] == "\n":
            cursor += 1

        out.append(html[pos:keep_to])
        pos, removed = cursor, removed + 1


def build():
    if not SRC.exists():
        raise SystemExit(
            f"missing {SRC.name}. It is gitignored on purpose — recover it with:\n"
            f"  git show 4d74a98:index.html > {SRC.name}"
        )

    html = SRC.read_text(encoding="utf-8")
    html, removed = strip_notes(html)

    # The S-for-notes hint is dead weight once the notes are gone.
    html = html.replace(" · <kbd>S</kbd> notes", "")

    # Disable the toggle too, so S can't slide up an empty panel. The #notes element
    # and its JS references stay put — removing them would null out `nb` downstream.
    toggle = "else if(k==='s'){notesOn=!notesOn;notes.classList.toggle('show',notesOn);}"
    if toggle not in html:
        raise SystemExit("notes key handler not found — build.py needs updating")
    html = html.replace(toggle, "")

    html = BANNER + html
    return html, removed


def main():
    html, removed = build()
    check = "--check" in sys.argv

    if check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else None
        if current != html:
            print(f"{OUT.name} is stale — run: python3 build.py")
            return 1
        print(f"{OUT.name} is up to date ({removed} notes blocks stripped)")
        return 0

    OUT.write_text(html, encoding="utf-8")
    kb = len(html.encode("utf-8")) / 1024
    print(f"wrote {OUT.name} — {removed} speaker-note blocks stripped, {kb:.0f}K")
    return 0


if __name__ == "__main__":
    sys.exit(main())
